/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.prescribeMedicine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author diyabaldota
 */
public class AddPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddPrescriptionJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem system;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount person;//userProcessContainer, enterprise, organization, system
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public AddPrescriptionJPanel(JPanel userProcessContainer, Enterprise enterprise, DoctorOrganization organization, EcoSystem system, UserAccount account, UserAccount person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = system;
        this.enterprise = enterprise;
        this.organization = organization;
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedicalList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMedList = new javax.swing.JTextArea();
        btnSubmitit = new javax.swing.JButton();
        icBack = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 848));
        setPreferredSize(new java.awt.Dimension(1440, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedicalList.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        lblMedicalList.setText("Medicine List:");
        add(lblMedicalList, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        txtMedList.setBackground(new java.awt.Color(204, 255, 255));
        txtMedList.setColumns(20);
        txtMedList.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        txtMedList.setForeground(new java.awt.Color(255, 255, 255));
        txtMedList.setRows(5);
        txtMedList.setBorder(null);
        jScrollPane1.setViewportView(txtMedList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, 100));

        btnSubmitit.setFont(new java.awt.Font("Optima", 0, 16)); // NOI18N
        btnSubmitit.setText("Submit");
        btnSubmitit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmititActionPerformed(evt);
            }
        });
        add(btnSubmitit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        icBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        icBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icBackMousePressed(evt);
            }
        });
        add(icBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, -1, -1));

        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lab.png"))); // NOI18N
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 870, 630));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmititActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmititActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblReq.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select a person's request to schedule");
            return;
        }
        Date d = new Date();
        System.out.println(d);
        //Date date = appointmentjDateChooser.getDate();
       try{
        if(appointmentjDateChooser.getDate().toString().length()<1){
            JOptionPane.showMessageDialog(this, "Please choose a date to schedule vaccination");
            return;
        }
        }
        catch(NullPointerException e){
            System.out.println("Null exception caught");
            JOptionPane.showMessageDialog(this, "Please select a date");
            return;
        }
        if(appointmentjDateChooser.getDate().before(d)){
            JOptionPane.showMessageDialog(this, "Please select a future date");
            return;
        }
        appointment req = (appointment)tblReq.getModel().getValueAt(selectedRow, 0);
        
        if(req.getStatus().equals("Approved")){
            JOptionPane.showMessageDialog(this, "Person is already scheduled an appointment");
            //System.out.println("Person is already scheduled a vaccination slot");
            return;
        }
        
        
        req.setStatus("Approved");
        dB4OUtil.storeSystem(system);
        populateTable();
//        btnPrescribeMed.setVisible(true);
//        btnTest.setVisible(true);


       
    }//GEN-LAST:event_btnSubmititActionPerformed

    private void icBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icBackMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_icBackMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitit;
    private javax.swing.JLabel icBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicalList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtMedList;
    // End of variables declaration//GEN-END:variables

    private boolean validate(String text) {
        return true;
    }
}
